version: 2.2

models:
  - name: stg_customers
    description: "description de la table client" 
    columns:
      - name: customer_id
        description: "Identifiant unique du client"
        tests:
          - unique
          - not_null
          
  - name: stg_categories
    columns:
      - name: category_id
        tests:
          - unique
          - not_null    

  - name: stg_employees
    description: "Description de la table categories"
    columns:
      - name: employee_id
        description: "Identifiant unique de la categorie"
        tests:
          - unique
          - not_null      

  - name: stg_orders
    description: "Description de la table employes"
    columns:
      - name: order_id
        description: "Identifiant unique de l'employe"
        tests:
          - unique
          - not_null

  - name: stg_products
    description: "Description de la table commandes"
    columns:
      - name: product_id
        description: "Identifiant unique du produit"
        tests:
          - unique
          - not_null

  - name: stg_shippers
    description: " Description de la table livreurs"
    columns:
      - name: shipper_id
        description: "Identifiant unique du livreur"
        tests:
          - unique
          - not_null    

  - name: stg_suppliers
    description: "Description de la table fournisseurs"
    columns:
      - name: supplier_id
        description: "Identifiant unique du fournisseur"
        tests:
          - unique
          - not_null   

  - name: stg_order_details
    description: "Description de la table de detail des commandes"
    columns:
        tests:
          -dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - order_id
              - product_id
    columns:
      - name: order_id
        description: "Identifiant de la commande"
        tests:
          - not_null
      - name: product_id
        description: "Identifiant du produit."
        tests:
          - not_null




