version: 2

sources:
  - name: northwind
    schema: public
    database: northwind
    description: "Source de données brutes PostgreSQL Northwind"
    tables:
      - name: customers
      - name: orders
      - name: order_details
      - name: products
      - name: categories
      - name: suppliers
      - name: employees
      - name: shippers